baseURL = "https://fists.cc/"
relativeURLs = true
languageCode = 'zh-cn'
title = 'Joe'
theme = 'PaperMod'

[imaging]
# 默认重采样过滤器，用于调整大小
resampleFilter = "box"
# 默认JPEG质量设置，默认为75
quality = 75
# 裁剪图片时使用的锚点，默认为"smart"
anchor = "smart"
# 默认背景色（用于不支持透明度的格式）
bgColor = "#ffffff"

[[menu.main]]
    identifier = "thinking"
    name = "Thinking"
    url = "/categories/thinking/"
    weight = 10

[menu]
  [[menu.main]]
    identifier = "products"
    name = "Products"
    url = "/categories/products/"
    weight = 20

  [[menu.main]]
    identifier = "leetcode"
    name = "LeetCode"
    url = "/categories/leetcode/"
    weight = 30

  [[menu.main]]
    identifier = "ai"
    name = "AI"
    url = "/categories/ai/"
    weight = 40
